### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by krishnakanthpps** [Meherdeep/agora-android-live-streaming#1]
Why is a there a black screen even when the App ID is placed.

**Comment by Meherdeep** [comment]
@krishnakanthpps Are you getting that black screen when you join in as a broadcaster as well?

**Comment by krishnakanthpps** [comment]
Yes. Both as a host and a audience as well. 

I believe only App ID needs to be placed.

**Comment by Meherdeep** [comment]
You're right. It was my fault, I forgot to add the user permission because of which you might be getting this black screen. However, I have resolved it. You can pull the code and test it out.

**Comment by krishnakanthpps** [comment]
Still the same issue. I deleted the app and reinstalled after compiling again and still same thing happens.

**Comment by Meherdeep** [comment]
@krishnakanthpps Can you please share your logs?

**Comment by krishnakanthpps** [comment]
[agoraapplogs.txt](https://github.com/Meherdeep/agora-android-live-streaming/files/6115150/agoraapplogs.txt)
Attached the logs

**Comment by krishnakanthpps** [comment]
Were you able to find anything. I am still stuck at that screen? 
![screen2](https://user-images.githubusercontent.com/4608088/110952831-aa315b00-836c-11eb-94f7-731b98d171b3.jpeg)
![screen1](https://user-images.githubusercontent.com/4608088/110952849-ad2c4b80-836c-11eb-82f2-1a716d77974c.jpeg)

**Comment by Meherdeep** [comment]
I don't see any error in the logs. Can you do the following checks:
1. Make sure that you're using the testing mode (App ID only) in the Agora dashboard
2. Make sure that you have a proper internet connection. If your internet connection is not good you can comment out the `setVideoEncoderConfiguration` lines

**Comment by krishnakanthpps** [comment]
Thank you.
